volumes:
  sistema-de-tarefas-data-db:

networks:
  sistema-de-tarefas:

services:
  db:
    image: postgres:16
    container_name: sistema-de-tarefas-db
    restart: always
    environment:
      POSTGRES_USER: suporte
      POSTGRES_PASSWORD: suporte
      POSTGRES_DB: dev
    expose:
    - 5432
    ports:
    - 5432:5432
    networks:
    - sistema-de-tarefas
    volumes:
    - sistema-de-tarefas-data-db:/var/lib/postgres/data
